# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
language: r
dist: bionic
cache: packages
latex: false
r_github_packages: mlr-org/mlr3book

addons:
  apt:
    packages:
       - lmodern
       - texlive-xetex
       - texlive-math-extra
       - texlive-base
       - texlive-binaries
       - texlive-fonts-extra
       - texlive-fonts-recommended
       - texlive-generic-recommended
       - texlive-humanities
       - texlive-latex-base
       - texlive-latex-extra
       - texlive-latex-recommended
       - texlive-pictures
       - texlive-publishers
       - texlive-science
       - ttf-dejavu


script:
  - make html
  - make pdf

deploy:
  provider: pages
  deploy.skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: 'bookdown/_book'
  keep_history: false
  fqdn: mlr3book.mlr-org.com
  on:
    branch: master
