language: r
cache:
  - packages
  - ccache

latex: false

addons:
  apt:
    packages:
       - lmodern
       - texlive-xetex
       - texlive-math-extra
       - texlive-base
       - texlive-binaries
       - texlive-fonts-extra
       - texlive-fonts-recommended
       - texlive-generic-recommended
       - texlive-humanities
       - texlive-latex-base
       - texlive-latex-extra
       - texlive-latex-recommended
       - texlive-pictures
       - texlive-publishers
       - texlive-science
       - fonts-roboto

before_install:
  - echo -e "options(Ncpus = 8, repos = structure(c(CRAN = 'https://cloud.r-project.org/')))" > $HOME/.Rprofile
  - mkdir $HOME/.R && echo -e 'CXX_STD = CXX14\n\nCC=ccache gcc -std=gnu99\nCXX=ccache g++\nC11=ccache g++\nC14=ccache g++\nFC=ccache gfortran\nF77=ccache gfortran' > $HOME/.R/Makevars
  - echo -e 'max_size = 5.0G\nsloppiness = include_file_ctime\nhash_dir=false' > $HOME/.ccache/ccache.conf
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (getRversion() < "3.2" && !requireNamespace("curl")) install.packages("curl")'
  - R -q -e 'remotes::install_github("ropenscilabs/tic"); print(tic::dsl_load()); tic::prepare_all_stages()'
  - R -q -e 'remotes::install_local()' # install mlr3book
  - R -q -e 'tic::before_install()'

install:
  - R -q -e 'tic::install()'

script: true

deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true

