# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages
latex: true
r_github_packages: mlr-org/mlr3book

script:
  - Rscript -e 'mlr3book::render_mlr3book()'

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: 'bookdown/_book'
  skip_cleanup: true
  keep_history: false
  fqdn: mlr3book.mlr-org.com
  on:
    branch: master

notifications:
  slack:
    on_pull_requests: false
    rooms:
      secure: mbxLAvp2v6CJdWhhqv8Awsw0usTXZUzirLyjKYd4giVcnmNDnn+qGgYnaXs5sWiAkzg3agZVg5Im4R9fq9wmrylWn2huebCg1wSgzJCy9FET88ZPrGZ4CW3h5gBBTwg2Iz5LE4nNGskLQqHESE3eLEQC9Lw3nJh2mme2mdz7GYtKlLPTjhBVCos3Ew2WVPiQ50rzB+/TuQ5mHh78CT4Iw1Vvo+J5u50eunLHpF0BMREp+UUCi6D/c3Ns8gDPyf7dFXF7n6j+K5KQ3OuoQcepBWHCR4SuUBiO2Elt8ikaVimn5sWBnZeuWskrNpagH3pV0bAvsZQhkfnvd69jr2f5Gx27Dd9J/woIrvgqrcUo6u2V2cQUF5AIyNu6Z597fDdNLoNeTvVu10HGJbbJOnRtMIzaqjApfcGRICnG48fPPSBil+bpz5rlXNltiqaRyF6fUrTdygeKjyV59ZqJBBVNJmR2bvm2ex7RNlaqzLNktrZJwkA7SROax6PrNUYOcLyw6oP0n8pBT+WjPjZnaVpAE0n927JiR3q/xwVnrV1qUJEhJ+6vHZUA4LHzQmN9ekQnZUVSEXBN9QMdLJ9EEzAcerP3GOvTGy/+5MzWRzPrrcm0yz7C/HdVLhWHghOUIj20GoWMx0Lcg7lBJd+X9xd3tiZFGviPm2N4AkkwtkTHvyE=
  on_success: change
  on_failure: change
