# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
language: r
dist: bionic
cache: packages
latex: true

script:
  - make install
  - make html
  # - make pdf

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: 'bookdown/_book'
  keep_history: false
  fqdn: mlr3book.mlr-org.com
  on:
    branch: master
